# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rustr_wrappers", use_symbols = TRUE, package_name = "rustr")

#' @docType package
#' @usage NULL
#' @useDynLib rustr, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Addition of Integers
#' @export
add_float <- function(x, y) .Call(wrap__add_float, x, y)
