# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rustr_wrappers", use_symbols = TRUE, package_name = "rustr")

#' @docType package
#' @usage NULL
#' @useDynLib rustr, .registration = TRUE
NULL

